#!/usr/bin/env python3
"""Turns TTF files into a C++ header so the plugin carries its fonts (NanoVG cannot read web fonts).
usage: embed_font.py out.hpp Name1=path1.ttf Name2=path2.ttf ...
produces: static const unsigned char k<Name>[] = {...}; static const unsigned int k<Name>Size = N;"""
import sys, os
out = sys.argv[1]
parts = ["// generated by tools/embed_font.py - do not edit\n#pragma once\n"]
for arg in sys.argv[2:]:
    name, path = arg.split("=", 1)
    data = open(path, "rb").read()
    parts.append(f"static const unsigned char k{name}[] = {{\n")
    for i in range(0, len(data), 24):
        parts.append(",".join(str(b) for b in data[i:i + 24]) + ",\n")
    parts.append(f"}};\nstatic const unsigned int k{name}Size = {len(data)};\n")
os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
open(out, "w").write("".join(parts))
print(f"{out}: {len(sys.argv) - 2} font(s)")
